[#8] Add plugin builder Dockerfiles
irods/irods_auth_plugin_pam_interactive pull request #10
Opened 2024-02-21 21:23 UTC by alanking

Addresses #8

Still testing the platforms:
- [ ] centos:7
- [ ] almalinux:8
- [ ] rockylinux:9
- [ ] debian:11
- [ ] debian:12
- [ ] ubuntu:20.04
- [ ] ubuntu:22.04

2024-02-21 22:00 UTC, korydraughn reviewed
Were these files taken from the development environment?

2024-02-21 22:48 UTC, korydraughn commented
I agree. Leveraging the dev environment Dockerfiles is the right step IMO.

2024-02-22 14:19 UTC, alanking commented
This was not as far along as I'd thought. Converting to draft. Will have this ready to go by COB today, I hope.

2024-02-22 19:31 UTC, alanking commented
Okay, got everything working. I went ahead and updated the CMakeLists file as well based on the CMakeLists in the irods/irods repo for plugins/auth.

2024-02-22 19:36 UTC, alanking commented
@SwooshyCueb - Feel free to have a look at this. I imagine we'll want to take another pass over this before the release, but this is just to get the ball rolling.

2024-02-22 20:43 UTC, korydraughn reviewed
Looks normal and boring.

Deferring to @SwooshyCueb for further review.

2024-02-22 20:43 UTC, korydraughn commented on CMakeLists.txt
>  )
A separate repo sounds fine.

Or, its inclusion is controlled via a build option.
If it's kept in this repo, no one has to go deal with another repo for testing.

Thoughts?

2024-02-22 20:54 UTC, korydraughn commented on CMakeLists.txt
>  )
Ohhh, got it.

Totally agree with you.

2024-02-22 20:55 UTC, korydraughn commented on CMakeLists.txt
>  )
Feel free to mark this resolved or leave it open for others to comment on.

2024-02-22 23:12 UTC, SwooshyCueb requested changes
Just a few notes

2024-02-22 23:12 UTC, SwooshyCueb commented on CMakeLists.txt
> +set(CPACK_DEBIAN_PACKAGE_DEPENDS "${IRODS_PACKAGE_DEPENDENCIES_STRING}, irods-server (= ${IRODS_VERSION}), irods-runtime (= ${IRODS_VERSION}), libc6")
add `libpam0g` to deb package depends.

2024-02-22 23:12 UTC, SwooshyCueb commented on CMakeLists.txt
> +set(CPACK_RPM_PACKAGE_REQUIRES "${IRODS_PACKAGE_DEPENDENCIES_STRING}, irods-server = ${IRODS_VERSION}, irods-runtime = ${IRODS_VERSION}")
add `pam` to rpm package requires.

2024-02-22 23:12 UTC, SwooshyCueb commented on CMakeLists.txt
> +  COMPONENT ${IRODS_PACKAGE_COMPONENT_RUNTIME_NAME}
We're only making one package, so no `COMPONENT` argument is needed.

2024-02-22 23:12 UTC, SwooshyCueb commented on CMakeLists.txt
> +  COMPONENT server
We're only making one package, so no `COMPONENT` argument is needed.

2024-02-22 23:12 UTC, SwooshyCueb commented on CMakeLists.txt
> +  COMPONENT ${IRODS_PACKAGE_COMPONENT_RUNTIME_NAME}
We're only making one package, so no `COMPONENT` argument is needed.

2024-02-22 23:12 UTC, SwooshyCueb commented on docker/builders/plugin_builder.centos7.Dockerfile
> +        gcc-c++ \
You'll want `centos-release-scl` as well. Our new clang externals package will depend on packages from the SCL repos.

2024-02-23 14:42 UTC, alanking commented on CMakeLists.txt
> +  COMPONENT ${IRODS_PACKAGE_COMPONENT_RUNTIME_NAME}
Done

2024-02-23 14:42 UTC, alanking commented on CMakeLists.txt
> +  COMPONENT server
Done

2024-02-23 14:42 UTC, alanking commented on CMakeLists.txt
> +  COMPONENT ${IRODS_PACKAGE_COMPONENT_RUNTIME_NAME}
Done

2024-02-23 14:42 UTC, alanking commented on docker/builders/plugin_builder.centos7.Dockerfile
> +        gcc-c++ \
Done

2024-02-23 14:43 UTC, alanking commented on CMakeLists.txt
> +list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "${CPACK_PACKAGING_INSTALL_PREFIX}${IRODS_HOME_DIRECTORY}/scripts/irods/test")
We will be adding tests for #6 and they will go into the usual spot for tests, so I think we should just leave these in. Thoughts?

2024-02-23 14:43 UTC, alanking commented on CMakeLists.txt
>  )
Done

2024-02-23 14:46 UTC, alanking commented on CMakeLists.txt
> +  COMPONENT server
Oh, good catch. Done

2024-02-23 14:49 UTC, SwooshyCueb commented on CMakeLists.txt
> +list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "${CPACK_PACKAGING_INSTALL_PREFIX}${IRODS_HOME_DIRECTORY}/scripts/irods/test")
Makes sense.

2024-02-23 18:29 UTC, korydraughn commented
Assuming #6 will be addressed in a different PR, is there anything left to do for this PR?

2024-02-23 18:30 UTC, alanking commented
I don't think so. I was able to build packages for all the platforms and they look kinda like what we want, at least for now, so that's the goal for this one.

2024-02-23 19:14 UTC, korydraughn commented
Cool. If you're happy with it, squash to taste.

2024-02-23 19:25 UTC, alanking commented
Squashed

2024-02-23 20:35 UTC, korydraughn approved these changes
Let's get an approval from @SwooshyCueb before pounding.

2024-02-23 21:42 UTC, SwooshyCueb approved these changes
LGTM

2024-02-23 22:00 UTC, merged